openapi: 3.0.0
info:
	title: API para cadastrar partidos
	description: API para cadastrar e gerenciar partidos e associados
	version: 1
	contact:
		name: Josiel Cardoso Mércio da Silva
		url: https://github.com/Scryter

Components:
	schemas:
		Partido:
			type: object
			properties:
				id:
					type:integer
					description: Id para identificação do partido no banco de dados
					example: 1
				nome:
				        type: string
				        description: "Nome do partido"
				        example: "Aliança Pelo Brasil"
        			sigla:
				        type: string
          				description: "Sigla do partido"
          				example: "APB"
        			ideologia:
          				type: enum
          				description: "Ideologia do partido"
          				example: "Direita"
        			
          			data_fundacao:	type: Date
          				description: "Data de fundação do partido"
          				example: "05/12/2019"
		Associado:
			type: object
			properties:
				id:
					type: integer
					description: identificador unico pessoal
				nome:
					type: String
					description: nome do associado
				cargoPolitico:
					type: enum
					description: cargo político ocupado
				sexo:
					type: enum
					description:
				data_nascimento:
					type: Date
					description: Data de nascimento

paths:
	/partidos:
		get:
			summary: requista informações dos partidos contido no banco de dados
			parameters:
				name: ideologia
				description: "Ideologia do partido"
				in: query
				schema:
					type: String
				required: false
				example: Direita
			responses:
				200:
					description: Sucesso
					content:
						application/json:
							schema:
								type: array
								items:
								$ref: #/components/schemas/Partido"
				404:
					description: Não encontrado
		 post:
      			summary: "registra um novo associado no sistema"
      			requestBody:
        			content:
     					application/json:
            					schema:
              						$ref: "#/components/schemas/AssociadoRequestBody"
              
      			responses:
        			201:
          				description: Criado com sucesso
          				content:
            					application/json:
              						schema:
                						$ref: "#/components/schemas/Associado"
        			400:
            				description: Parâmetros incorretos foram enviados na requisição
 /associados/{id}:
	parameters: 
		name: id
      		description: "Id do associado"
      		in: path
      			schema:
        			type: integer
      				required: true
      				example: 1
    		get:
      			summary: obtém informações de um associado
      			responses:
        			200: 
          				description: sucesso
          				content:
            					application/json:
                					schema:
                  						$ref: "#/components/schemas/Associado"
        			404:
          				description: Não encontrado
    		put:
      			summary: atualiza as informações de um associado
      			requestBody:
        			content:
          				application/json:
            					schema:
              						$ref: "#/components/schemas/AssociadoRequestBody"
      			responses:
        			200:
          				description: Atualizado com sucesso
        			400:
            				description: Parâmetros incorretos foram enviados na requisição
        			404:
            				description: Não encontrado
            
    				delete:
      					summary: Deleta um partido
      					responses:
        					200:
          						description: deletado com sucesso
        					404:
          						description: Não encontrado
  